services
  db:
    image: mysql:5.7
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: rootpass
  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./www:/var/www/html
    links:
      - db:mysql
  phpmyadmin:
    image: corbinu/docker-phpmyadmin
    links:
      - db:mysql
    ports:
      - 8181:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: rootpass