wordpress:
  image: wordpress
  ports:
    - 8080:80
  volumes:
    - ./www:/var/www/html
  links:
    - db:mysql
db:
  image: mysql:5.7
  environment: 
    MYSQL_ROOT_PASSWORD: rootpass
phpmyadmin:
  image: corbinu/docker-phpmyadmin
  links:
    - db:mysql
  ports:
    - 8181:80
  environment:
    MYSQL_USERNAME: root
    MYSQL_ROOT_PASSWORD: rootpass